### ISSUE TITLE
ImportError: No module named cli

### ISSUE THREAD

**Issue by thesonyman** [vivescere/yajuu#4]
C:\Windows\system32>yajuu media download --media 'Code geass season 1'
Traceback (most recent call last):
  File "C:\Python27\Scripts\yajuu-script.py", line 9, in <module>
    load_entry_point('yajuu==0.3.0', 'console_scripts', 'yajuu')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2229, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\yajuu\yajuu.py", line 1, in <module>
    from yajuu.cli import cli
ImportError: No module named cli

Any ideas I think it's because I don't have the development version of python installed but this is windows.
When I try to install cli this happens.
![see](https://cloud.githubusercontent.com/assets/7980428/18623065/754bd782-7ded-11e6-90f2-c1abf9946005.PNG)

**Comment by vivescere** [comment]
Hello! Are you trying to install the development version? I'm currently completely rewriting it. Could you install the stable version from master instead?

**Comment by vivescere** [comment]
I also did not long ago a video on how to install all the dependencies, but the framerate is horrible, and you'll have to run `pip3 install git+https://github.com/vivescere/yajuu.git` instead of `
pip install git+https://github.com/vivescere/yajuu.git@develop`. Finally, you can ignore the nodejs part: I removed that dependency from [the project that I use to pass the cloudflare verifiction](https://github.com/Anorov/cloudflare-scrape) via a pull request.

The video is [here](https://www.youtube.com/watch?v=yjSTsjU-jz4).

**Comment by thesonyman** [comment]
oh woops I thought this was python 2.7 thanks for responding.
